swagger: 2
info:
  title: Citrination
  version: 1.0.0
  description: API for access to Citrination
  termsOfService: 'https://citrination.com/tos'
  contact:
    name: Citrine Informatics
    email: admin@citrine.io
    url: 'https://citrine.io'
  license:
    name: Apache License Version 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
schemes:
  - https
host: citrination.com
basePath: /api
consumes:
  - application/json
produces:
  - application/json
security:
  - ApiKeyAuth: []
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key
paths:
  $ref: ./paths/index.yaml
definitions:
  DatasetReturningQuery:
    type: object
    description: A query that returns information about datasets.
    allOf:
      - type: object
        description: Base type for all queries against Citrination.
        properties:
          fromIndex:
            type: number
            format: integer
            nullable: true
            default: null
            description: >-
              The index of the first record to return. This is used for
              pagination through results.
          size:
            type: number
            format: integer
            nullable: true
            default: null
            description: >-
              The number of records to return. This is used for pagination
              through results. The number of hits that are returned will never
              be greater than this number, but may be smaller if there are fewer
              records in the scope of the query or if the maximum number of
              records that the server will allow to be returned is exceeded
              (this is typically 100).
          randomResults:
            type: boolean
            nullable: true
            default: null
            description: >-
              Whether a random set of results should be returned. If not
              specified, the default value is false.
          randomSeed:
            type: number
            format: int32
            nullable: true
            default: null
            description: >-
              The seed to the pseudo-random number generator used to generate
              random results. If not specified, a value based on the current
              time will be used. This should be used when paginating through
              results; if not specified, a different random seed will be
              generated for each request and there may be duplicate records
              between sets of results.
          scoreRelevance:
            type: boolean
            nullable: true
            default: null
            description: >-
              Whether to score relevance in queries. If not specified, the
              relevancy score is not tracked.
          returnMaxScore:
            type: boolean
            nullable: true
            default: null
            description: >-
              Whether to return the maximum score over all hits in scope, not
              just the results that are returned. This only has meaning when
              scoreRelevance is set to true. If not specified, the default value
              of this settings is false.
      - properties:
          query:
            type: array
            items:
              $ref: ../../core/query/DataQuery
            nullable: true
            default: null
            description: Queries against the content of datasets and/or PIF records.
          countPifs:
            type: boolean
            nullable: true
            default: null
            description: >-
              Whether to count the number of PIFs in scope of the current query
              within each dataset. If there are no queries against the content
              of the PIFs, then this will return the total number of PIFs in the
              dataset. If there are queries against PIF content, then this will
              return the number of PIFs in each dataset that matched that query.
  DatasetSearchResult:
    type: object
    description: The result of a single query for datasets on Citrination.
    allOf:
      - type: object
        description: The base type for all search results against Citrination.
        properties:
          took:
            type: number
            format: int64
            nullable: true
            default: null
            description: >-
              The number of milliseconds that the query took to execute on the
              Citrination server. This does _not_ include the latency in the
              request being sent to Citrination or returned to the local
              machine.
          totalNumHits:
            type: number
            format: int64
            nullable: true
            default: null
            description: >-
              The total number of hits against the query that was executed. The
              number of hits returned from the server may be significantly less
              than this due to the pagination of results.
          maxScore:
            type: number
            format: double
            nullable: true
            default: null
            description: >-
              The maximum score for all hits against the query that was executed
              (not simple the max score of the hits in the current paginated set
              of results).
      - properties:
          hits:
            type: array
            items:
              type: object
              description: A single dataset that matched a query run against Citrination.
              properties:
                score:
                  type: number
                  format: double
                  nullable: true
                  default: null
                  description: >-
                    The relevancy score for the dataset against the executed
                    query.
                id:
                  type: string
                  nullable: true
                  default: null
                  description: The unique ID of the dataset.
                name:
                  type: string
                  nullable: true
                  default: null
                  description: The owner-defined name of the dataset.
                description:
                  type: string
                  nullable: true
                  default: null
                  description: The owner-defined description of the dataset.
                owner:
                  type: string
                  nullable: true
                  default: null
                  description: The name of the owner of the dataset.
                email:
                  type: string
                  nullable: true
                  default: null
                  description: The email address of the owner of the dataset.
                isFeatured:
                  type: boolean
                  nullable: true
                  default: null
                  description: >-
                    Whether the dataset is a featured one. A null value implies
                    that the dataset is not featured.
                numPifs:
                  type: number
                  format: int64
                  nullable: true
                  default: null
                  description: >-
                    When requested in the query, this is the number of PIFs that
                    are in the dataset and match any filters on the content of
                    PIF systems.
                updatedAt:
                  type: string
                  nullable: true
                  default: null
                  description: The date and time that the dataset record was last updated.
            nullable: true
            default: null
            description: >-
              The current set of paginated hits again the query that was
              executed.

