swagger: 2
info:
  title: Citrination
  version: 1.0.0
  description: API for access to Citrination
  termsOfService: 'https://citrination.com/tos'
  contact:
    name: Citrine Informatics
    email: admin@citrine.io
    url: 'https://citrine.io'
  license:
    name: Apache License Version 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
schemes: https
host: citrination.com
basePath: api
consumes:
  - application/json
produces:
  - application/json
security:
  - ApiKeyAuth: []
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key
paths:
  $ref: ./paths/index.yaml
definitions:
  System:
    type: object
    description: A generic representation of a physical system.
    discriminator:
      propertyName: type
      mapping:
        system: System
        system.chemical: ChemicalSystem
    required:
      - type
    properties:
      type:
        type: string
        enum:
          - system
          - system.chemical
        description: Internal system type for this object.
      uid:
        type: string
        nullable: true
        default: null
        description: >-
          An ID for this system that is unique within the dataset that contains
          it on Citrination.
      names:
        type: array
        items:
          type: string
        nullable: true
        default: null
        description: Common names of the system.
      ids:
        type: array
        items:
          $ref: ../core/Id.yaml
        nullable: true
        default: null
        description: Any identifiers (named labels) that apply to the system.
      classifications:
        type: array
        items:
          $ref: ../core/Classification.yaml
        nullable: true
        default: null
        description: Any classifications (unambiguous categories) that apply to the system.
      source:
        nullable: true
        default: null
        $ref: ../core/Source.yaml
      quantity:
        nullable: true
        default: null
        $ref: ../core/Quantity.yaml
      properties:
        type: array
        items:
          $ref: ../core/Property.yaml
        nullable: true
        default: null
        description: Observations made on the system.
      preparation:
        type: array
        items:
          $ref: ../core/ProcessStep.yaml
        nullable: true
        default: null
        description: An ordered list of steps used to produce the system.
      subSystems:
        type: array
        items:
          $ref: ./System.yaml
        nullable: true
        default: null
        description: Any sub-systems of this system.
      references:
        type: array
        items:
          $ref: ../core/Reference.yaml
        nullable: true
        default: null
        description: Published references for this sytem.
      contacts:
        type: array
        items:
          $ref: ../core/Person.yaml
        nullable: true
        default: null
        description: People to contact for information about the system.
      licenses:
        type: array
        items:
          $ref: ../core/License.yaml
        nullable: true
        default: null
        description: Licenses that apply to the data in this record.
      tags:
        type: array
        items:
          type: string
        nullable: true
        default: null
        description: Any number of tags to apply to the object.

