swagger: 2.0
info:
    $ref: ./info/index.yaml
schemes:
    - https
host: citrination.com
basePath: /api
consumes:
    - application/json
produces:
    - application/json
security:
    - ApiKeyAuth: []
securityDefinitions:
    $ref: ./securityDefinitions/index.yaml
paths:
    $ref: ./paths/index.yaml
definitions:
    $ref: ./definitions/index.yaml
